#!/usr/bin/python3

import sys
import time

def factorize(num):
    '''
    Takes a number as input.

    Args:
        num: input integer.

    Return:
        A tuple of two factors if the number is not a prime.
        None if the number is prime.
    '''
    factors = None
    for a in range(2, int(num**0.5)+1):
        if num % a == 0:
            factors = (a, num // a)
            break
    return factors

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start_time = time.time()

    for line in lines:
        num = int(line.strip())
        factors = factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")

    elapsed_time = time.time() - start_time
    if elapsed_time > 5:
       print("Time limit exceeded")
