#!/usr/bin/python3

import sys
import math


def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def factorize(num):
    if is_prime(num):
        return f"{num} is prime."

    for i in range(2, num + 1):
        if num % i == 0 and is_prime(i) and is_prime(num // i):
            return f"{num}={i}*{num // i}"


def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <filename>")
        return

    filename = sys.argv[1]

    try:
        with open(filename, 'r') as file:
            num = int(file.readline().strip())
            result = factorize(num)
            print(result)

    except FileNotFoundError:
        print(f"File not found: {filename}")
    except ValueError:
        print(f"Invalid number in {filename}")


if __name__ == '__main__':
    main()
